- name: Disable Default Nginx
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable Nginx 24
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: get secrets
  ansible.builtin.set_fact:
    secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'roboshop-{{ env }}/data/{{ component_name }} token={{ vault_token }} url=http://vault-internal.salman06.shop:8200') }}"

- name: Copy nginx config file
  ansible.builtin.template:
    src: default.conf
    dest: /etc/nginx/default.conf

- name: Remove old app content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create app content directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true

