# source common.sh
#
# print_head Copy RabbitmQ repo file
# cp rabbitmq.repo /etc/yum.repos.d/rabbitmq.repo &>>$log_file
#
# print_head Install RabbitmQ Server
# dnf install rabbitmq-server -y &>>$log_file
#
# print_head Start RabbitMQ Service
# systemctl enable rabbitmq-server &>>$log_file
# systemctl start rabbitmq-server &>>$log_file
#
# print_head Add application user
# rabbitmqctl add_user roboshop roboshop123 &>>$log_file
# rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" &>>$log_file

- name: Copy RabbitMQ file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install RabbitmQ Server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: started

- name: Add application user
  ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"


- name: Install Prometheus Node exporter
  ansible.builtin.include_role:
    name: common
    tasks_from: prom-node-exporter