- name: Install docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker.repo


- name: Install docker
  become: yes
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Start docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: yes
