- name: Install Go
  ansible.builtin.dnf:
    name:
      - golang
    state: installed

- name: Include artifact_download
  ansible.builtin.include_tasks:
    file: artifact_download.yml

- name: Install Go Dependencies
  ansible.builtin.shell: go mod init ; go get ; go build
  args:
    chdir: /app
  become: true


- name: Include systemd_setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml












