- name: Install Go
  ansible.builtin.dnf:
    name:
      - golang
    state: installed

- name: Include artifact_download
  ansible.builtin.include_tasks:
    file: artifact_download.yaml

- name: Install Go Dependencies
  ansible.builtin.shell: sudo go mod init myapp ; sudo go get ; sudo go build;
  args:
    chdir: /app


- name: Include systemd_setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yaml












